[package]
name = "xet_logging"
version = "0.14.5"
edition = "2024"

[dependencies]
xet_runtime = { path = "../xet_runtime" }
error_printer = { path = "../error_printer" }
utils = { path = "../utils" }

chrono = { workspace = true }
console-subscriber = { workspace = true, optional = true }
git-version = { workspace = true }
sysinfo = { workspace = true }
tracing = { workspace = true }
tracing-appender = { workspace = true }
tracing-subscriber = { workspace = true }

[features]
default = []
tokio-console = ["dep:console-subscriber"]

[[bin]]
name = "log_test_executable"
path = "tests/bin/log_test_executable.rs"

[dev-dependencies]
tempfile = { workspace = true }
rand = { workspace = true }
