[package]
name = "xet_config"
version = "0.14.5"
edition = "2024"

[lib]
name = "xet_config"
path = "src/lib.rs"

[dependencies]
utils = { path = "../utils" }
konst = "0.4"
const-str = "1.1"

[dev-dependencies]
serial_test = { workspace = true }

[features]
no-default-cache = []
