[package]
name = "config"
version = "0.14.5"
edition = "2024"

[lib]
name = "config"
path = "src/lib.rs"

[dependencies]
merklehash = { path = "../merklehash" }
utils = { path = "../utils" }
ctor = { workspace = true }
duration-str = { workspace = true }
lazy_static = { workspace = true }
tracing = { workspace = true }
paste = { workspace = true }

[dev-dependencies]
serial_test = { workspace = true }
